# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfstatesubst" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "53149a29e8c1137ff4231668e4c2e7eff28c772c958c67f41687e03667d96c5a"
      url "https://github.com/abicky/tfstatesubst/releases/download/v#{version}/tfstatesubst_darwin_amd64.tar.gz"
      rename "tfstatesubst_darwin_amd64/tfstatesubst", "tfstatesubst"
    end
    on_arm do
      sha256 "1810d942740d0f60087b5414968bce998e7b62dbe3bd37a5b1a48309328b6790"
      url "https://github.com/abicky/tfstatesubst/releases/download/v#{version}/tfstatesubst_darwin_arm64.tar.gz"
      rename "tfstatesubst_darwin_arm64/tfstatesubst", "tfstatesubst"
    end
  end

  on_linux do
    on_intel do
      sha256 "613d15bdcac97a3ef44ebc5507db055f78fb86089b5b0a6773c1f435866dc83d"
      url "https://github.com/abicky/tfstatesubst/releases/download/v#{version}/tfstatesubst_linux_amd64.tar.gz"
      rename "tfstatesubst_linux_amd64/tfstatesubst", "tfstatesubst"
    end
    on_arm do
      sha256 "c7564f24a9f00123b9f8882a54463c2011b5ee281af43e2247c82ea308f59a11"
      url "https://github.com/abicky/tfstatesubst/releases/download/v#{version}/tfstatesubst_linux_arm64.tar.gz"
      rename "tfstatesubst_linux_arm64/tfstatesubst", "tfstatesubst"
    end
  end

  name "tfstatesubst"
  desc "Substitute Terraform state values into restricted Go templates"
  homepage "https://github.com/abicky/tfstatesubst"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfstatesubst"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfstatesubst"]
    end
  end
  generate_completions_from_executable "tfstatesubst", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
