# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfstatesubst" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "aa0e94e2052e26fa3cb7bc890e3efd4b4bf87dc09faa4512cecc234f819bf8e8"
      url "https://github.com/abicky/tfstatesubst/releases/download/v#{version}/tfstatesubst_darwin_amd64.tar.gz"
      rename "tfstatesubst_darwin_amd64/tfstatesubst", "tfstatesubst"
    end
    on_arm do
      sha256 "131456876936e583c4fb3b946b520527fefd98b13c2c09c9b94208546ee7b1d8"
      url "https://github.com/abicky/tfstatesubst/releases/download/v#{version}/tfstatesubst_darwin_arm64.tar.gz"
      rename "tfstatesubst_darwin_arm64/tfstatesubst", "tfstatesubst"
    end
  end

  on_linux do
    on_intel do
      sha256 "af3c08e5bd9e2b8f61f3a8227883d735845b84c3005fee64a8de0ef4442eab25"
      url "https://github.com/abicky/tfstatesubst/releases/download/v#{version}/tfstatesubst_linux_amd64.tar.gz"
      rename "tfstatesubst_linux_amd64/tfstatesubst", "tfstatesubst"
    end
    on_arm do
      sha256 "b397588f9642465ba0dfe0aef17ed52528d7c51590a3b5f6a72d06d65aa4234e"
      url "https://github.com/abicky/tfstatesubst/releases/download/v#{version}/tfstatesubst_linux_arm64.tar.gz"
      rename "tfstatesubst_linux_arm64/tfstatesubst", "tfstatesubst"
    end
  end

  name "tfstatesubst"
  desc "Substitute Terraform state values into restricted Go templates"
  homepage "https://github.com/abicky/tfstatesubst"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfstatesubst"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfstatesubst"]
    end
  end
  generate_completions_from_executable "tfstatesubst", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
