# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akv < Formula
  desc "A CLI tool for injecting Azure Key Vault secrets"
  homepage "https://github.com/abicky/akv"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abicky/akv/releases/download/v0.1.1/akv_darwin_amd64.tar.gz"
      sha256 "293906793782a096fe94b48da113cd23765e08cca71cadf2c7c59d7ecbeda240"

      def install
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abicky/akv/releases/download/v0.1.1/akv_darwin_arm64.tar.gz"
      sha256 "079e9449fef704499162d853d19ec94689c5af80f3701bf3951ea6f97b47e89f"

      def install
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abicky/akv/releases/download/v0.1.1/akv_linux_amd64.tar.gz"
        sha256 "809a986fb8993e630a8b81ae45c77caafedce8ae120e15fffca6a031e4a4806b"

        def install
          bin.install "akv"
          generate_completions_from_executable(bin/"akv", "completion")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abicky/akv/releases/download/v0.1.1/akv_linux_arm64.tar.gz"
        sha256 "9b727b6bf8f650fd8af52bc25edf6b745048f818810749b094cb037fd3973b9f"

        def install
          bin.install "akv"
          generate_completions_from_executable(bin/"akv", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/akv --version"
  end
end
