# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akv < Formula
  desc "A CLI tool for injecting Azure Key Vault secrets"
  homepage "https://github.com/abicky/akv"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abicky/akv/releases/download/v0.1.3/akv_darwin_amd64.tar.gz"
      sha256 "367911c92ab9a792238b8d8357dea2d37b858967c38b310be4e7fe20c3744d63"

      define_method(:install) do
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abicky/akv/releases/download/v0.1.3/akv_darwin_arm64.tar.gz"
      sha256 "d5f4369ed46bf24b86d5cb5c87dcada46e353d3c5a44d1af41eb4eb3ea10a02a"

      define_method(:install) do
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abicky/akv/releases/download/v0.1.3/akv_linux_amd64.tar.gz"
      sha256 "1098d1d99ebf8d196a434848c0c15897c9363bb925434eb49d28a608f2321c87"
      define_method(:install) do
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abicky/akv/releases/download/v0.1.3/akv_linux_arm64.tar.gz"
      sha256 "c7e941804c1b77a7afe89c0822e6413b532bc498a77758d6505b46029814da8b"
      define_method(:install) do
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
  end

  test do
    system "#{bin}/akv --version"
  end
end
