# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akv < Formula
  desc "A CLI tool for injecting Azure Key Vault secrets"
  homepage "https://github.com/abicky/akv"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abicky/akv/releases/download/v0.1.4/akv_darwin_amd64.tar.gz"
      sha256 "9ad379eef2bdd715573681a14f46c547f9b3d670d9eb1020e8b65ef019cef264"

      define_method(:install) do
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abicky/akv/releases/download/v0.1.4/akv_darwin_arm64.tar.gz"
      sha256 "326bc8e540440ce3898583e2506fb7eff07fa23103f6bdfe32467765a457e9ec"

      define_method(:install) do
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abicky/akv/releases/download/v0.1.4/akv_linux_amd64.tar.gz"
      sha256 "586b5e8ad1c0e0cf6683551694a74a978b9e80a67980ed59d23e4de092c7cc1d"
      define_method(:install) do
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abicky/akv/releases/download/v0.1.4/akv_linux_arm64.tar.gz"
      sha256 "b381f4f8edf154071ee5f25d396b66a0acfd2437ad89fbf642cc34545bff0873"
      define_method(:install) do
        bin.install "akv"
        generate_completions_from_executable(bin/"akv", "completion")
      end
    end
  end

  test do
    system "#{bin}/akv --version"
  end
end
