# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsmec < Formula
  desc "A CLI tool for Amazon ECS that provides some commands to execute bothersome operations"
  homepage "https://github.com/abicky/ecsmec"
  version "0.1.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.2/ecsmec_darwin_amd64.tar.gz"
    sha256 "6fad31400f2bb106ae5c37ffb140222705e38f41c7186b31ea49a2e8dba379fc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.2/ecsmec_linux_amd64.tar.gz"
    sha256 "59e5bed8e124ce7f8835a1d7c188d1878011c3df245be30b11d6502412af23e5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.2/ecsmec_linux_arm64.tar.gz"
    sha256 "074a8994fd229ff27887b186b39e67f848e63ac5fa676b54282fba790cb27558"
  end

  def install
    bin.install "ecsmec"
  end

  test do
    system "#{bin}/ecsmec --version"
  end
end
