# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsmec < Formula
  desc "A CLI tool for Amazon ECS that provides some commands to execute bothersome operations"
  homepage "https://github.com/abicky/ecsmec"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.1/ecsmec_darwin_amd64.tar.gz"
    sha256 "8a0659ecb9ee4faa8f52aa0641a58e4d6e79d94c5e77eafadfceb35061cd8f91"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.1/ecsmec_linux_amd64.tar.gz"
    sha256 "54d5d40e068972377f9670ec92cf44610ef6546175a49e1c922ea718231996c2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.1/ecsmec_linux_arm64.tar.gz"
    sha256 "9dfa424abb198082899090e1d3836540b89284a773abda59317a5da07993c954"
  end

  def install
    bin.install "ecsmec"
  end

  test do
    system "#{bin}/ecsmec --version"
  end
end
