# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsmec < Formula
  desc "A CLI tool for Amazon ECS that provides some commands to execute bothersome operations"
  homepage "https://github.com/abicky/ecsmec"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.0/ecsmec_darwin_amd64.tar.gz"
    sha256 "f47ae657de564eec6cfac8d788f26d851feeed92b1344735b567315633880cef"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.0/ecsmec_linux_amd64.tar.gz"
    sha256 "c7599acb33a62c6da97890f47d63a3711ef3ebf436da001f349bebfb1633bd5d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/abicky/ecsmec/releases/download/v0.1.0/ecsmec_linux_arm64.tar.gz"
    sha256 "fe10ad371ba0463d4862db37f8a7633c53bf62ba493a095f8f3dcdcc2f05f259"
  end

  def install
    bin.install "ecsmec"
  end

  test do
    system "#{bin}/ecsmec --version"
  end
end
