# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PdShift < Formula
  desc "A CLI tool for managing PagerDuty on-call shifts"
  homepage "https://github.com/abicky/pd-shift"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abicky/pd-shift/releases/download/v0.1.1/pd-shift_darwin_amd64.tar.gz"
      sha256 "6c611d81d02b38b9782241ec4973a9efae95b711cbddce2ac19746dd6035f19c"

      def install
        bin.install "pd-shift"
        generate_completions_from_executable(bin/"pd-shift", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abicky/pd-shift/releases/download/v0.1.1/pd-shift_darwin_arm64.tar.gz"
      sha256 "e406a0917eeddf8d889f18d19109b832fac51d1a37652549ae2bed225c78f499"

      def install
        bin.install "pd-shift"
        generate_completions_from_executable(bin/"pd-shift", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/abicky/pd-shift/releases/download/v0.1.1/pd-shift_linux_amd64.tar.gz"
      sha256 "f7936e26242f738deb037cea812d19f3623bc1034957f6544ab9f4a1b585a239"
      def install
        bin.install "pd-shift"
        generate_completions_from_executable(bin/"pd-shift", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/abicky/pd-shift/releases/download/v0.1.1/pd-shift_linux_arm64.tar.gz"
      sha256 "cfbd486b87dbdcfd31faf751861563b827755daf1bed4880f098bced77d22a51"
      def install
        bin.install "pd-shift"
        generate_completions_from_executable(bin/"pd-shift", "completion")
      end
    end
  end

  test do
    system "#{bin}/pd-shift --version"
  end
end
