# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PdShift < Formula
  desc "A CLI tool for managing PagerDuty on-call shifts"
  homepage "https://github.com/abicky/pd-shift"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abicky/pd-shift/releases/download/v0.1.0/pd-shift_darwin_amd64.tar.gz"
      sha256 "9dfc00e39b5be21fea28f2a7da1b9efa68922b5cf6db1e490cc0cd2c6f0f58c6"

      def install
        bin.install "pd-shift"
        generate_completions_from_executable(bin/"pd-shift", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abicky/pd-shift/releases/download/v0.1.0/pd-shift_darwin_arm64.tar.gz"
      sha256 "f3f7b163ae6b0ab124bb2db563dc4627251517b11b54a62fcd8941b1d5d045f9"

      def install
        bin.install "pd-shift"
        generate_completions_from_executable(bin/"pd-shift", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/abicky/pd-shift/releases/download/v0.1.0/pd-shift_linux_amd64.tar.gz"
      sha256 "7c44dff7db5d102d748840070ab55a4f43ff604fffa40fcdf891dc73280a7f4c"
      def install
        bin.install "pd-shift"
        generate_completions_from_executable(bin/"pd-shift", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/abicky/pd-shift/releases/download/v0.1.0/pd-shift_linux_arm64.tar.gz"
      sha256 "9edf03f5cecc1c18f64a8aedece11dd14f33286078555eefa15ebcafcc4bcb37"
      def install
        bin.install "pd-shift"
        generate_completions_from_executable(bin/"pd-shift", "completion")
      end
    end
  end

  test do
    system "#{bin}/pd-shift --version"
  end
end
